version: '3.1'

volumes:
  node_frontend:
  node_backend:


services:
  backend:
    build:
      context: ./SuperAGIBackend
      dockerfile: Dockerfile.production
    restart: always
    environment:
      PORT: "5000"
      DB_HOST: "$DB_HOST"
      DB_PORT: "$DB_PORT"
      DB_TYPE: "$DB_TYPE"
      DB_USER: "$DB_USER"
      DB_NAME: "$DB_NAME"
      DB_PASS: "$DB_PASS"
      OPENAI_KEY: "$OPENAI_KEY"
    ports:
      - "5000"
    volumes:
      - node_backend:/app/node_modules

  frontend_with_proxy:
    build:
      context: ./SuperAGIFrontend
      dockerfile: Dockerfile.production
    restart: always
    volumes:
      - node_frontend:/app/node_modules
    ports:
      - "${PORT}:80"
