version: '3.1'

volumes:
  node_frontend:
  node_backend:
  psql_volume:


services:
  psql:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: super_shortener
    volumes:
      - psql_volume:/var/lib/postgresql/data
    ports:
      - "5432"
      - "5010:5432"
  backend:
    build:
      context: ./SuperAGIBackend
      dockerfile: Dockerfile.production
    restart: always
    env_file:
      - .env
    depends_on:
      - psql
    ports:
      - "5000"
    volumes:
      - node_backend:/app/node_modules

  frontend_with_proxy:
    build:
      context: ./SuperAGIFrontend
      dockerfile: Dockerfile.production
    restart: always
    environment:
      PORT: "80"
    volumes:
      - node_frontend:/app/node_modules
    ports:
      - "80:80"
