FROM node:18-alpine

WORKDIR /app
RUN npm install -g pnpm
COPY package.json ./
COPY pnpm-lock.yaml ./

RUN pnpm install

COPY . .

RUN pnpm run build

ENV NODE_ENV=production

CMD ["/bin/bash","-c","pnpm typeorm:run-migrations && pnpm start:prod"]
