FROM node:18-alpine

WORKDIR /app
RUN npm install -g pnpm
COPY package.json ./
COPY pnpm-lock.yaml ./

RUN pnpm install

ENV NODE_ENV=development

CMD ["/bin/bash","-c","pnpm typeorm:run-migrations && pnpm start:debug"]


