FROM node:18

WORKDIR /app
RUN npm install -g pnpm typescript ts-node
COPY package.json ./
COPY pnpm-lock.yaml ./

RUN pnpm install

COPY . .

RUN pnpm run build

ENV NODE_ENV=production

CMD ["/bin/bash","-c","pnpm run-migrations && pnpm start:prod"]
