FROM node:18

WORKDIR /app
RUN npm install -g pnpm typescript ts-node
COPY package.json ./
COPY pnpm-lock.yaml ./

RUN pnpm install

ENV NODE_ENV=development

CMD ["/bin/bash","-c","pnpm run-migrations && pnpm start:debug"]


